[package]
name = "resource_killer"
version = "0.1.0"
authors = ["Pagwin <Pagwin.Fedora@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.*"
